-- SCHOOL OF LIFE SYSTEM DATABASE SCHEMA
-- Copy and paste this script into your Supabase Dashboard SQL Editor (https://supabase.com/dashboard/project/tvyhsjcxscoyqkhnazwa/sql)

-- 1. PROFILES TABLE (User Accounts, Roles & Approvals)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  member_id TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL DEFAULT 'COMMUNITY_MEMBER', -- 'ADMIN', 'VOLUNTEER', 'COMMUNITY_MEMBER', 'CORE_MEMBER'
  status TEXT NOT NULL DEFAULT 'APPROVED', -- default is APPROVED for instant signup
  username TEXT,
  email TEXT,
  password TEXT,
  age INTEGER,
  waiver_consent BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) but allow anonymous reads/writes for testing convenience
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.profiles FOR UPDATE USING (true);

-- 2. ANNOUNCEMENTS TABLE
CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  date TEXT NOT NULL,
  body TEXT NOT NULL,
  reactions JSONB NOT NULL DEFAULT '{}'::jsonb,
  comments JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.announcements FOR INSERT WITH CHECK (true);

-- 3. EVENTS TABLE
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  location TEXT NOT NULL,
  skills TEXT[] NOT NULL,
  attendance JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.events FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.events FOR UPDATE USING (true);

-- 4. BADGES TABLE
CREATE TABLE IF NOT EXISTS public.badge_data (
  profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  swimming BOOLEAN[] DEFAULT '{false, false, false}'::boolean[],
  fishing BOOLEAN[] DEFAULT '{false, false, false}'::boolean[],
  kayaking BOOLEAN[] DEFAULT '{false, false, false}'::boolean[],
  archery BOOLEAN[] DEFAULT '{false, false, false}'::boolean[],
  cooking BOOLEAN[] DEFAULT '{false, false, false}'::boolean[],
  outdoorsmanship BOOLEAN[] DEFAULT '{false, false, false}'::boolean[]
);

ALTER TABLE public.badge_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.badge_data FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.badge_data FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.badge_data FOR UPDATE USING (true);

-- 5. SELF ATTESTED SKILLS TABLE
CREATE TABLE IF NOT EXISTS public.self_attested (
  profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  skills JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE public.self_attested ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.self_attested FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.self_attested FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.self_attested FOR UPDATE USING (true);

-- 6. SEED INITIAL USERS DATABASE (For Demo / Login testing)
INSERT INTO public.profiles (name, member_id, role, status) VALUES 
('Ayman Suh', 'SOL-2026-01', 'ADMIN', 'APPROVED'),
('Lucas Miller', 'SOL-2026-02', 'COMMUNITY_MEMBER', 'APPROVED'),
('Emma Watson', 'SOL-2026-03', 'VOLUNTEER', 'APPROVED'),
('Sophia Chen', 'SOL-2026-04', 'CORE_MEMBER', 'APPROVED'),
('Marcus Vance', 'SOL-2026-05', 'COMMUNITY_MEMBER', 'PENDING')
ON CONFLICT (member_id) DO NOTHING;

-- Seed default empty merit badges for seeded users
INSERT INTO public.badge_data (profile_id, swimming, fishing, kayaking, archery, cooking, outdoorsmanship)
SELECT id, '{true, true, false}', '{true, false, false}', '{true, true, true}', '{true, false, false}', '{true, true, false}', '{true, true, false}'
FROM public.profiles WHERE member_id = 'SOL-2026-01' ON CONFLICT DO NOTHING;

INSERT INTO public.badge_data (profile_id, swimming, fishing, kayaking, archery, cooking, outdoorsmanship)
SELECT id, '{true, false, false}', '{true, false, false}', '{true, true, true}', '{false, false, false}', '{true, false, false}', '{true, false, false}'
FROM public.profiles WHERE member_id = 'SOL-2026-02' ON CONFLICT DO NOTHING;

INSERT INTO public.badge_data (profile_id, swimming, fishing, kayaking, archery, cooking, outdoorsmanship)
SELECT id, '{true, false, false}', '{true, true, true}', '{true, false, false}', '{true, true, false}', '{true, false, false}', '{false, false, false}'
FROM public.profiles WHERE member_id = 'SOL-2026-03' ON CONFLICT DO NOTHING;

INSERT INTO public.badge_data (profile_id, swimming, fishing, kayaking, archery, cooking, outdoorsmanship)
SELECT id, '{true, true, true}', '{true, true, false}', '{true, true, false}', '{true, true, true}', '{true, true, true}', '{true, true, true}'
FROM public.profiles WHERE member_id = 'SOL-2026-04' ON CONFLICT DO NOTHING;

-- Seed self attested entries
INSERT INTO public.self_attested (profile_id, skills)
SELECT id, '{"Outdoor Navigation": false, "Knot Tying Mastery": false, "Swimming Safety": false, "Camp Cooking Basics": false, "Camp Tool Maintenance": false, "Archery Target Practice": false}'::jsonb
FROM public.profiles ON CONFLICT DO NOTHING;
